config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  body       :text(65535)
#  name       :string(255)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Board < ApplicationRecord
  has_many :comments
  
  validates :name, presence: true, length: { maximum: 10 }
  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }
end

app/models/commemt.rb
# == Schema Information
#
# Table name: commemts
#
#  id         :integer          not null, primary key
#  comment    :text(65535)      not null
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer
#
# Indexes
#
#  index_commemts_on_board_id  (board_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#

class Commemt < ApplicationRecord
  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_target_board, only: %i[show edit update destroy]

  def index
    @boards = Board.page(params[:page])
  end

  def new
    @board = Board.new(flash[:board])
  end

  def create
    board = Board.new(board_params)
    if board.save
      flash[:notice] = "「#{board.title}」の掲示板を作成しました"
      redirect_to board
    else
      redirect_to new_board_path, flash: {
        borad: board,
        error_messages: board.errors.full_messages
      }
    end
  end

  def show
  end

  def edit
  end

  def update
    @board.update(board_params)

    redirect_to @board
  end

  def destroy
    @board.delete
    redirect_to boards_path, flash: { notice: "「#{@board.title}」の掲示板が削除されました"}
  end
  
  private

  def board_params
    params.require(:board).permit(:name, :title, :body)
  end

  def set_target_board
    @board = Board.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= board.title %></h4>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(board.body) %></p>
    <p class="text-right font-weight-bold mr-10"><%= board.name %></p>
  </div>
</div>

app/views/boards/_form.html.erb
<% if flash[:error_messages] %>
<div class="alert alert-danger">
  <ul>
    <% flash[:error_messages].each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for board do |f| %>
<div class="form-group">
  <%= f.label :name, '名前' %>
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :title, 'タイトル' %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :body, '本文' %>
  <%= f.text_area :body, class: 'form-control', rows: 10 %>
</div>
<%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板編集</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<%= render partial: 'form', locals: { board: @board } %>

app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板一覧</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '新規作成', new_board_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<% if flash[:notice] %>
<div class="alert alert-danger"><%= flash[:notice] %></div>
<% end %>
<table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
    <tr>
      <td><%= board.id %></td>
      <td><%= board.title %></td>
      <td><%= board.name %></td>
      <td><%= board.created_at.to_s(:datetime_jp) %></td>
      <td><%= board.updated_at.to_s(:datetime_jp) %></td>
      <td><%= link_to '詳細', board, class: 'btn btn-outline-dark'%></td>
      <td><%= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @boards %>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<%= render partial: 'form', locals: { board: @board } %>

app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
    <%= link_to '編集', edit_board_path(@board), class: 'btn btn-outline-dark' %>
  </div>
</div>

<% if flash[:notice] %>
<div class="alert alert-primary"><%= flash[:notice] %></div>
<% end %>


<%= render @board %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>App</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <%= yield %>
  </div>
</body>

</html>